name: intro-plasma
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  # Jupyter dependencies
  - jupyterhub>=4.1.6,<5
  - jupyterlab>=4.4,<5
  - notebook>=7.4,<8
  - jupyter-resource-usage>=1,<2
  - jupyterlab-topbar-text >=1.1.0,<2
  - nodejs>=20
  # Python environment
  - python>=3.10
  - pip
  - ipywidgets>=8,<9
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - biopython
  # Jupyter archive
  # https://github.com/jupyterlab-contrib/jupyter-archive
  - jupyter-archive
  # JupyterLab git
  # https://github.com/jupyterlab/jupyterlab-git
  - jupyterlab-git
  # R environment
  - r-irkernel
  - r-base>=4
  - r-tidyverse
  # JupyterLab Variable inspector
  # https://github.com/lckr/jupyterlab-variableInspector
  - r-repr
  - jupyterlab-variableinspector
  - pip:
  # Print module version
    - watermark
  # Bash environment
    - bash_kernel
